const _ = require('lodash');

const countries = [
    {"name": "Afghanistan", "iso3": "AFG", "wikipage": "https://fr.wikipedia.org/wiki/Afghanistan", "capital": "Kaboul"},
    {"name": "Afrique du Sud", "iso3": "ZAF", "wikipage": "https://fr.wikipedia.org/wiki/Afrique_du_Sud", "capital": "Pretoria"},
    {"name": "Albanie", "iso3": "ALB", "wikipage": "https://fr.wikipedia.org/wiki/Albanie", "capital": "Tirana"},
    {"name": "Algérie", "iso3": "DZA", "wikipage": "https://fr.wikipedia.org/wiki/Alg%C3%A9rie", "capital": "Alger"},
    {"name": "Allemagne", "iso3": "DEU", "wikipage": "https://fr.wikipedia.org/wiki/Allemagne", "capital": "Berlin"},
    {"name": "Andorre", "iso3": "AND", "wikipage": "https://fr.wikipedia.org/wiki/Andorre", "capital": "Andorre-la-Vieille"},
    {"name": "Angola", "iso3": "AGO", "wikipage": "https://fr.wikipedia.org/wiki/Angola", "capital": "Luanda"},
    {"name": "Antigua-et-Barbuda", "iso3": "ATG", "wikipage": "https://fr.wikipedia.org/wiki/Antigua-et-Barbuda", "capital": "Saint John's"},
    {"name": "Arabie saoudite", "iso3": "SAU", "wikipage": "https://fr.wikipedia.org/wiki/Arabie_saoudite", "capital": "Riyad"},
    {"name": "Argentine", "iso3": "ARG", "wikipage": "https://fr.wikipedia.org/wiki/Argentine", "capital": "Buenos Aires"},
    {"name": "Arménie", "iso3": "ARM", "wikipage": "https://fr.wikipedia.org/wiki/Arm%C3%A9nie", "capital": "Erevan"},
    {"name": "Australie", "iso3": "AUS", "wikipage": "https://fr.wikipedia.org/wiki/Australie", "capital": "Canberra"},
    {"name": "Autriche", "iso3": "AUT", "wikipage": "https://fr.wikipedia.org/wiki/Autriche", "capital": "Vienne"},
    {"name": "Azerbaïdjan", "iso3": "AZE", "wikipage": "https://fr.wikipedia.org/wiki/Azerba%C3%AFdjan", "capital": "Bakou"},
    {"name": "Bahamas", "iso3": "BHS", "wikipage": "https://fr.wikipedia.org/wiki/Bahamas", "capital": "Nassau"},
    {"name": "Bahreïn", "iso3": "BHR", "wikipage": "https://fr.wikipedia.org/wiki/Bahre%C3%AFn", "capital": "Manama"},
    {"name": "Bangladesh", "iso3": "BGD", "wikipage": "https://fr.wikipedia.org/wiki/Bangladesh", "capital": "Dacca"},
    {"name": "Barbade", "iso3": "BRB", "wikipage": "https://fr.wikipedia.org/wiki/Barbade", "capital": "Bridgetown"},
    {"name": "Belgique", "iso3": "BEL", "wikipage": "https://fr.wikipedia.org/wiki/Belgique", "capital": "Bruxelles"},
    {"name": "Belize", "iso3": "BLZ", "wikipage": "https://fr.wikipedia.org/wiki/Belize", "capital": "Belmopan"},
    {"name": "Bénin", "iso3": "BEN", "wikipage": "https://fr.wikipedia.org/wiki/B%C3%A9nin", "capital": "Porto-Novo"},
    {"name": "Bhoutan", "iso3": "BTN", "wikipage": "https://fr.wikipedia.org/wiki/Bhoutan", "capital": "Thimbu"},
    {"name": "Birmanie", "iso3": "MMR", "wikipage": "https://fr.wikipedia.org/wiki/Birmanie", "capital": "Naypyidaw"},
    {"name": "Bolivie", "iso3": "BOL", "wikipage": "https://fr.wikipedia.org/wiki/Bolivie", "capital": "Sucre"},
    {"name": "Bosnie-Herzégovine", "iso3": "BIH", "wikipage": "https://fr.wikipedia.org/wiki/Bosnie-Herz%C3%A9govine", "capital": "Sarajevo"},
    {"name": "Botswana", "iso3": "BWA", "wikipage": "https://fr.wikipedia.org/wiki/Botswana", "capital": "Gaborone"},
    {"name": "Brésil", "iso3": "BRA", "wikipage": "https://fr.wikipedia.org/wiki/Br%C3%A9sil", "capital": "Brasilia"},
    {"name": "Brunei", "iso3": "BRN", "wikipage": "https://fr.wikipedia.org/wiki/Brunei", "capital": "Bandar Seri Begawan"},
    {"name": "Bulgarie", "iso3": "BGR", "wikipage": "https://fr.wikipedia.org/wiki/Bulgarie", "capital": "Sofia"},
    {"name": "Burkina Faso", "iso3": "BFA", "wikipage": "https://fr.wikipedia.org/wiki/Burkina_Faso", "capital": "Ouagadougou"},
    {"name": "Burundi", "iso3": "BDI", "wikipage": "https://fr.wikipedia.org/wiki/Burundi", "capital": "Bujumbura"},
    {"name": "Cambodge", "iso3": "KHM", "wikipage": "https://fr.wikipedia.org/wiki/Cambodge", "capital": "Phnom Penh"},
    {"name": "Cameroun", "iso3": "CMR", "wikipage": "https://fr.wikipedia.org/wiki/Cameroun", "capital": "Yaoundé"},
    {"name": "Canada", "iso3": "CAN", "wikipage": "https://fr.wikipedia.org/wiki/Canada", "capital": "Ottawa"},
    {"name": "Cap-Vert", "iso3": "CPV", "wikipage": "https://fr.wikipedia.org/wiki/Cap-Vert", "capital": "Praia"},
    {"name": "Chili", "iso3": "CHL", "wikipage": "https://fr.wikipedia.org/wiki/Chili", "capital": "Santiago"},
    {"name": "Chypre", "iso3": "CYP", "wikipage": "https://fr.wikipedia.org/wiki/Chypre_(pays)", "capital": "Nicosie"},
    {"name": "Colombie", "iso3": "COL", "wikipage": "https://fr.wikipedia.org/wiki/Colombie", "capital": "Bogota"},
    {"name": "Comores", "iso3": "COM", "wikipage": "https://fr.wikipedia.org/wiki/Comores_(pays)", "capital": "Moroni"},
    {"name": "Corée du Nord", "iso3": "PRK", "wikipage": "https://fr.wikipedia.org/wiki/Cor%C3%A9e_du_Nord", "capital": "Pyongyang"},
    {"name": "Corée du Sud", "iso3": "KOR", "wikipage": "https://fr.wikipedia.org/wiki/Cor%C3%A9e_du_Sud", "capital": "Séoul"},
    {"name": "Costa Rica", "iso3": "CRI", "wikipage": "https://fr.wikipedia.org/wiki/Costa_Rica", "capital": "San José"},
    {"name": "Côte d'Ivoire", "iso3": "CIV", "wikipage": "https://fr.wikipedia.org/wiki/C%C3%B4te_d%27Ivoire", "capital": "Yamoussoukro"},
    {"name": "Croatie", "iso3": "HRV", "wikipage": "https://fr.wikipedia.org/wiki/Croatie", "capital": "Zagreb"},
    {"name": "Cuba", "iso3": "CUB", "wikipage": "https://fr.wikipedia.org/wiki/Cuba", "capital": "La Havane"},
    {"name": "Djibouti", "iso3": "DJI", "wikipage": "https://fr.wikipedia.org/wiki/Djibouti", "capital": "Djibouti"},
    {"name": "Dominique", "iso3": "DMA", "wikipage": "https://fr.wikipedia.org/wiki/Dominique_(pays)", "capital": "Roseau"},
    {"name": "Égypte", "iso3": "EGY", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89gypte", "capital": "Le Caire"},
    {"name": "Émirats arabes unis", "iso3": "ARE", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89mirats_arabes_unis", "capital": "Abu Dhabi"},
    {"name": "Équateur", "iso3": "ECU", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89quateur_(pays)", "capital": "Quito"},
    {"name": "Érythrée", "iso3": "ERI", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89rythr%C3%A9e", "capital": "Asmara"},
    {"name": "Espagne", "iso3": "ESP", "wikipage": "https://fr.wikipedia.org/wiki/Espagne", "capital": "Madrid"},
    {"name": "Estonie", "iso3": "EST", "wikipage": "https://fr.wikipedia.org/wiki/Estonie", "capital": "Tallinn"},
    {"name": "États-Unis", "iso3": "USA", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89tats-Unis", "capital": "Washington"},
    {"name": "Éthiopie", "iso3": "ETH", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89thiopie", "capital": "Addis-Abeba"},
    {"name": "Fidji", "iso3": "FJI", "wikipage": "https://fr.wikipedia.org/wiki/Fidji", "capital": "Suva"},
    {"name": "Finlande", "iso3": "FIN", "wikipage": "https://fr.wikipedia.org/wiki/Finlande", "capital": "Helsinki"},
    {"name": "France", "iso3": "FRA", "wikipage": "https://fr.wikipedia.org/wiki/France", "capital": "Paris"},
    {"name": "Gabon", "iso3": "GAB", "wikipage": "https://fr.wikipedia.org/wiki/Gabon", "capital": "Libreville"},
    {"name": "Gambie", "iso3": "GMB", "wikipage": "https://fr.wikipedia.org/wiki/Gambie", "capital": "Banjul"},
    {"name": "Géorgie", "iso3": "GEO", "wikipage": "https://fr.wikipedia.org/wiki/G%C3%A9orgie_(pays)", "capital": "Tbilissi"},
    {"name": "Ghana", "iso3": "GHA", "wikipage": "https://fr.wikipedia.org/wiki/Ghana", "capital": "Accra"},
    {"name": "Grèce", "iso3": "GRC", "wikipage": "https://fr.wikipedia.org/wiki/Gr%C3%A8ce", "capital": "Athènes"},
    {"name": "Grenade", "iso3": "GRD", "wikipage": "https://fr.wikipedia.org/wiki/Grenade_(pays)", "capital": "Saint George's"},
    {"name": "Guatemala", "iso3": "GTM", "wikipage": "https://fr.wikipedia.org/wiki/Guatemala", "capital": "Guatemala"},
    {"name": "Guinée", "iso3": "GIN", "wikipage": "https://fr.wikipedia.org/wiki/Guin%C3%A9e", "capital": "Conakry"},
    {"name": "Guinée équatoriale", "iso3": "GNQ", "wikipage": "https://fr.wikipedia.org/wiki/Guin%C3%A9e_%C3%A9quatoriale", "capital": "Malabo"},
    {"name": "Guinée-Bissau", "iso3": "GNB", "wikipage": "https://fr.wikipedia.org/wiki/Guin%C3%A9e-Bissau", "capital": "Bissau"},
    {"name": "Guyana", "iso3": "GUY", "wikipage": "https://fr.wikipedia.org/wiki/Guyana", "capital": "Georgetown"},
    {"name": "Haïti", "iso3": "HTI", "wikipage": "https://fr.wikipedia.org/wiki/Ha%C3%AFti", "capital": "Port-au-Prince"},
    {"name": "Honduras", "iso3": "HND", "wikipage": "https://fr.wikipedia.org/wiki/Honduras", "capital": "Tegucigalpa"},
    {"name": "Hongrie", "iso3": "HUN", "wikipage": "https://fr.wikipedia.org/wiki/Hongrie", "capital": "Budapest"},
    {"name": "île Maurice", "iso3": "MUS", "wikipage": "https://fr.wikipedia.org/wiki/Maurice_(pays)", "capital": "Port Louis"},
    {"name": "îles Marshall", "iso3": "MHL", "wikipage": "https://fr.wikipedia.org/wiki/%C3%8Eles_Marshall", "capital": "Majuro"},
    {"name": "Inde", "iso3": "IND", "wikipage": "https://fr.wikipedia.org/wiki/Inde", "capital": "New Delhi"},
    {"name": "Indonésie", "iso3": "IDN", "wikipage": "https://fr.wikipedia.org/wiki/Indon%C3%A9sie", "capital": "Jakarta"},
    {"name": "Irak", "iso3": "IRQ", "wikipage": "https://fr.wikipedia.org/wiki/Irak", "capital": "Bagdad"},
    {"name": "Iran", "iso3": "IRN", "wikipage": "https://fr.wikipedia.org/wiki/Iran", "capital": "Téhéran"},
    {"name": "Irlande", "iso3": "IRL", "wikipage": "https://fr.wikipedia.org/wiki/Irlande_(pays)", "capital": "Dublin"},
    {"name": "Islande", "iso3": "ISL", "wikipage": "https://fr.wikipedia.org/wiki/Islande", "capital": "Reykjavik"},
    {"name": "Israël", "iso3": "ISR", "wikipage": "https://fr.wikipedia.org/wiki/Isra%C3%ABl", "capital": "Jérusalem"},
    {"name": "Italie", "iso3": "ITA", "wikipage": "https://fr.wikipedia.org/wiki/Italie", "capital": "Rome"},
    {"name": "Jamaïque", "iso3": "JAM", "wikipage": "https://fr.wikipedia.org/wiki/Jama%C3%AFque", "capital": "Kingston"},
    {"name": "Japon", "iso3": "JPN", "wikipage": "https://fr.wikipedia.org/wiki/Japon", "capital": "Tokyo"},
    {"name": "Jordanie", "iso3": "JOR", "wikipage": "https://fr.wikipedia.org/wiki/Jordanie", "capital": "Amman"},
    {"name": "Kazakhstan", "iso3": "KAZ", "wikipage": "https://fr.wikipedia.org/wiki/Kazakhstan", "capital": "Astana"},
    {"name": "Kenya", "iso3": "KEN", "wikipage": "https://fr.wikipedia.org/wiki/Kenya", "capital": "Nairobi"},
    {"name": "Kirghizistan", "iso3": "KGZ", "wikipage": "https://fr.wikipedia.org/wiki/Kirghizistan", "capital": "Bichkek"},
    {"name": "Kiribati", "iso3": "KIR", "wikipage": "https://fr.wikipedia.org/wiki/Kiribati", "capital": "Tarawa"},
    {"name": "Koweït", "iso3": "KWT", "wikipage": "https://fr.wikipedia.org/wiki/Kowe%C3%AFt", "capital": "Koweït"},
    {"name": "Laos", "iso3": "LAO", "wikipage": "https://fr.wikipedia.org/wiki/Laos", "capital": "Vientiane"},
    {"name": "Lesotho", "iso3": "LSO", "wikipage": "https://fr.wikipedia.org/wiki/Lesotho", "capital": "Maseru"},
    {"name": "Lettonie", "iso3": "LVA", "wikipage": "https://fr.wikipedia.org/wiki/Lettonie", "capital": "Riga"},
    {"name": "Liban", "iso3": "LBN", "wikipage": "https://fr.wikipedia.org/wiki/Liban", "capital": "Beyrouth"},
    {"name": "Liberia", "iso3": "LBR", "wikipage": "https://fr.wikipedia.org/wiki/Liberia", "capital": "Monrovia"},
    {"name": "Libye", "iso3": "LBY", "wikipage": "https://fr.wikipedia.org/wiki/Libye", "capital": "Tripoli"},
    {"name": "Liechtenstein", "iso3": "LIE", "wikipage": "https://fr.wikipedia.org/wiki/Liechtenstein", "capital": "Vaduz"},
    {"name": "Lituanie", "iso3": "LTU", "wikipage": "https://fr.wikipedia.org/wiki/Lituanie", "capital": "Vilnius"},
    {"name": "Luxembourg", "iso3": "LUX", "wikipage": "https://fr.wikipedia.org/wiki/Luxembourg_(pays)", "capital": "Luxembourg"},
    {"name": "Madagascar", "iso3": "MDG", "wikipage": "https://fr.wikipedia.org/wiki/Madagascar", "capital": "Antananarivo"},
    {"name": "Malaisie", "iso3": "MYS", "wikipage": "https://fr.wikipedia.org/wiki/Malaisie", "capital": "Kuala Lumpur"},
    {"name": "Malawi", "iso3": "MWI", "wikipage": "https://fr.wikipedia.org/wiki/Malawi", "capital": "Lilongwe"},
    {"name": "Maldives", "iso3": "MDV", "wikipage": "https://fr.wikipedia.org/wiki/Maldives", "capital": "Malé"},
    {"name": "Mali", "iso3": "MLI", "wikipage": "https://fr.wikipedia.org/wiki/Mali", "capital": "Bamako"},
    {"name": "Malte", "iso3": "MLT", "wikipage": "https://fr.wikipedia.org/wiki/Malte", "capital": "La Valette"},
    {"name": "Maroc", "iso3": "MAR", "wikipage": "https://fr.wikipedia.org/wiki/Maroc", "capital": "Rabat"},
    {"name": "Mauritanie", "iso3": "MRT", "wikipage": "https://fr.wikipedia.org/wiki/Mauritanie", "capital": "Nouakchott"},
    {"name": "Mexique", "iso3": "MEX", "wikipage": "https://fr.wikipedia.org/wiki/Mexique", "capital": "Mexico"},
    {"name": "Micronésie", "iso3": "FSM", "wikipage": "https://fr.wikipedia.org/wiki/%C3%89tats_f%C3%A9d%C3%A9r%C3%A9s_de_Micron%C3%A9sie", "capital": "Palikir"},
    {"name": "République de Moldavie", "iso3": "MDA", "wikipage": "https://fr.wikipedia.org/wiki/Moldavie", "capital": "Chisinau"},
    {"name": "Monaco", "iso3": "MCO", "wikipage": "https://fr.wikipedia.org/wiki/Monaco", "capital": "Monaco"},
    {"name": "Mongolie", "iso3": "MNG", "wikipage": "https://fr.wikipedia.org/wiki/Mongolie", "capital": "Oulan-Bator"},
    {"name": "Monténégro", "iso3": "MNE", "wikipage": "https://fr.wikipedia.org/wiki/Mont%C3%A9n%C3%A9gro", "capital": "Podgorica"},
    {"name": "Mozambique", "iso3": "MOZ", "wikipage": "https://fr.wikipedia.org/wiki/Mozambique", "capital": "Maputo"},
    {"name": "Namibie", "iso3": "NAM", "wikipage": "https://fr.wikipedia.org/wiki/Namibie", "capital": "Windhoek"},
    {"name": "Nauru", "iso3": "NRU", "wikipage": "https://fr.wikipedia.org/wiki/Nauru", "capital": "Yaren"},
    {"name": "Népal", "iso3": "NPL", "wikipage": "https://fr.wikipedia.org/wiki/N%C3%A9pal", "capital": "Katmandou"},
    {"name": "Nicaragua", "iso3": "NIC", "wikipage": "https://fr.wikipedia.org/wiki/Nicaragua", "capital": "Managua"},
    {"name": "Niger", "iso3": "NER", "wikipage": "https://fr.wikipedia.org/wiki/Niger", "capital": "Niamey"},
    {"name": "Nigeria", "iso3": "NGA", "wikipage": "https://fr.wikipedia.org/wiki/Nigeria", "capital": "Abuja"},
    {"name": "Norvège", "iso3": "NOR", "wikipage": "https://fr.wikipedia.org/wiki/Norv%C3%A8ge", "capital": "Oslo"},
    {"name": "Nouvelle-Zélande", "iso3": "NZL", "wikipage": "https://fr.wikipedia.org/wiki/Nouvelle-Z%C3%A9lande", "capital": "Wellington"},
    {"name": "Oman", "iso3": "OMN", "wikipage": "https://fr.wikipedia.org/wiki/Oman", "capital": "Mascate"},
    {"name": "Ouganda", "iso3": "UGA", "wikipage": "https://fr.wikipedia.org/wiki/Ouganda", "capital": "Kampala"},
    {"name": "Ouzbékistan", "iso3": "UZB", "wikipage": "https://fr.wikipedia.org/wiki/Ouzb%C3%A9kistan", "capital": "Tachkent"},
    {"name": "Pakistan", "iso3": "PAK", "wikipage": "https://fr.wikipedia.org/wiki/Pakistan", "capital": "Islamabad"},
    {"name": "Palaos", "iso3": "PLW", "wikipage": "https://fr.wikipedia.org/wiki/Palaos", "capital": "Melekeok"},
    {"name": "Panama", "iso3": "PAN", "wikipage": "https://fr.wikipedia.org/wiki/Panama", "capital": "Panama"},
    {"name": "Papouasie-Nouvelle-Guinée", "iso3": "PNG", "wikipage": "https://fr.wikipedia.org/wiki/Papouasie-Nouvelle-Guin%C3%A9e", "capital": "Port Moresby"},
    {"name": "Paraguay", "iso3": "PRY", "wikipage": "https://fr.wikipedia.org/wiki/Paraguay", "capital": "Asunción"},
    {"name": "Pays-Bas", "iso3": "NLD", "wikipage": "https://fr.wikipedia.org/wiki/Pays-Bas", "capital": "Amsterdam"},
    {"name": "Pérou", "iso3": "PER", "wikipage": "https://fr.wikipedia.org/wiki/P%C3%A9rou", "capital": "Lima"},
    {"name": "Philippines", "iso3": "PHL", "wikipage": "https://fr.wikipedia.org/wiki/Philippines", "capital": "Manille"},
    {"name": "Pologne", "iso3": "POL", "wikipage": "https://fr.wikipedia.org/wiki/Pologne", "capital": "Varsovie"},
    {"name": "Portugal", "iso3": "PRT", "wikipage": "https://fr.wikipedia.org/wiki/Portugal", "capital": "Lisbonne"},
    {"name": "Qatar", "iso3": "QAT", "wikipage": "https://fr.wikipedia.org/wiki/Qatar", "capital": "Doha"},
    {"name": "République centrafricaine", "iso3": "CAF", "wikipage": "https://fr.wikipedia.org/wiki/R%C3%A9publique_centrafricaine", "capital": "Bangui"},
    {"name": "République de Macédoine", "iso3": "FYR", "wikipage": "https://fr.wikipedia.org/wiki/Mac%C3%A9doine_(pays)", "capital": "Skopje"},
    {"name": "République démocratique du Congo", "iso3": "COD", "wikipage": "https://fr.wikipedia.org/wiki/R%C3%A9publique_d%C3%A9mocratique_du_Congo", "capital": "Kinshasa"},
    {"name": "République dominicaine", "iso3": "DOM", "wikipage": "https://fr.wikipedia.org/wiki/R%C3%A9publique_dominicaine", "capital": "Saint-Domingue"},
    {"name": "République du Congo", "iso3": "COG", "wikipage": "https://fr.wikipedia.org/wiki/R%C3%A9publique_du_Congo", "capital": "Brazzaville"},
    {"name": "République populaire de Chine", "iso3": "CHN", "wikipage": "https://fr.wikipedia.org/wiki/Chine", "capital": "Pékin"},
    {"name": "République socialiste soviétique de Biélorussie", "iso3": "BLR", "wikipage": "https://fr.wikipedia.org/wiki/Bi%C3%A9lorussie", "capital": "Minsk"},
    {"name": "République tchèque", "iso3": "CZE", "wikipage": "https://fr.wikipedia.org/wiki/R%C3%A9publique_tch%C3%A8que", "capital": "Prague"},
    {"name": "Roumanie", "iso3": "ROU", "wikipage": "https://fr.wikipedia.org/wiki/Roumanie", "capital": "Bucarest"},
    {"name": "Royaume-Uni", "iso3": "GBR", "wikipage": "https://fr.wikipedia.org/wiki/Royaume-Uni", "capital": "Londres"},
    {"name": "Russie", "iso3": "RUS", "wikipage": "https://fr.wikipedia.org/wiki/Russie", "capital": "Moscou"},
    {"name": "Rwanda", "iso3": "RWA", "wikipage": "https://fr.wikipedia.org/wiki/Rwanda", "capital": "Kigali"},
    {"name": "Saint-Marin", "iso3": "SMR", "wikipage": "https://fr.wikipedia.org/wiki/Saint-Marin", "capital": "Saint-Marin"},
    {"name": "Saint-Vincent-et-les-Grenadines", "iso3": "VCT", "wikipage": "https://fr.wikipedia.org/wiki/Saint-Vincent-et-les-Grenadines", "capital": "Kingstown"},
    {"name": "Sainte-Lucie", "iso3": "LCA", "wikipage": "https://fr.wikipedia.org/wiki/Sainte-Lucie", "capital": "Castries"},
    {"name": "Salomon", "iso3": "SLB", "wikipage": "https://fr.wikipedia.org/wiki/%C3%8Eles_Salomon_(%C3%89tat)", "capital": "Honiara"},
    {"name": "Salvador", "iso3": "SLV", "wikipage": "https://fr.wikipedia.org/wiki/Salvador", "capital": "San Salvador"},
    {"name": "Samoa", "iso3": "WSM", "wikipage": "https://fr.wikipedia.org/wiki/Samoa", "capital": "Apia"},
    {"name": "São Tomé et Príncipe", "iso3": "STP", "wikipage": "https://fr.wikipedia.org/wiki/Sao_Tom%C3%A9-et-Principe", "capital": "São Tomé"},
    {"name": "Sénégal", "iso3": "SEN", "wikipage": "https://fr.wikipedia.org/wiki/S%C3%A9n%C3%A9gal", "capital": "Dakar"},
    {"name": "République de Serbie", "iso3": "SRB", "wikipage": "https://fr.wikipedia.org/wiki/Serbie", "capital": "Belgrade"},
    {"name": "Seychelles", "iso3": "SYC", "wikipage": "https://fr.wikipedia.org/wiki/Seychelles", "capital": "Victoria"},
    {"name": "Sierra Leone", "iso3": "SLE", "wikipage": "https://fr.wikipedia.org/wiki/Sierra_Leone", "capital": "Freetown"},
    {"name": "Singapour", "iso3": "SGP", "wikipage": "https://fr.wikipedia.org/wiki/Singapour", "capital": "Singapour"},
    {"name": "Slovaquie", "iso3": "SVK", "wikipage": "https://fr.wikipedia.org/wiki/Slovaquie", "capital": "Bratislava"},
    {"name": "Slovénie", "iso3": "SVN", "wikipage": "https://fr.wikipedia.org/wiki/Slov%C3%A9nie", "capital": "Ljubljana"},
    {"name": "Somalie", "iso3": "SOM", "wikipage": "https://fr.wikipedia.org/wiki/Somalie", "capital": "Mogadiscio"},
    {"name": "Soudan", "iso3": "SDN", "wikipage": "https://fr.wikipedia.org/wiki/Soudan", "capital": "Khartoum"},
    {"name": "Soudan du Sud", "iso3": "SSD", "wikipage": "https://fr.wikipedia.org/wiki/Soudan_du_Sud", "capital": "Djouba"},
    {"name": "Sri Lanka", "iso3": "LKA", "wikipage": "https://fr.wikipedia.org/wiki/Sri_Lanka", "capital": "Sri Jayawardenapura"},
    {"name": "Suède", "iso3": "SWE", "wikipage": "https://fr.wikipedia.org/wiki/Su%C3%A8de", "capital": "Stockholm"},
    {"name": "Suisse", "iso3": "CHE", "wikipage": "https://fr.wikipedia.org/wiki/Suisse", "capital": "Berne"},
    {"name": "Suriname", "iso3": "SUR", "wikipage": "https://fr.wikipedia.org/wiki/Suriname", "capital": "Paramaribo"},
    {"name": "Swaziland", "iso3": "SWZ", "wikipage": "https://fr.wikipedia.org/wiki/Swaziland", "capital": "Mbabane"},
    {"name": "Syrie", "iso3": "SYR", "wikipage": "https://fr.wikipedia.org/wiki/Syrie", "capital": "Damas"},
    {"name": "Tadjikistan", "iso3": "TJK", "wikipage": "https://fr.wikipedia.org/wiki/Tadjikistan", "capital": "Douchanbe"},
    {"name": "Tanzanie", "iso3": "TZN", "wikipage": "https://fr.wikipedia.org/wiki/Tanzanie", "capital": "Dodoma"},
    {"name": "Tchad", "iso3": "TCD", "wikipage": "https://fr.wikipedia.org/wiki/Tchad", "capital": "N'Djamena"},
    {"name": "Thaïlande", "iso3": "THA", "wikipage": "https://fr.wikipedia.org/wiki/Tha%C3%AFlande", "capital": "Bangkok"},
    {"name": "Timor oriental", "iso3": "TLS", "wikipage": "https://fr.wikipedia.org/wiki/Timor_oriental", "capital": "Dili"},
    {"name": "Togo", "iso3": "TGO", "wikipage": "https://fr.wikipedia.org/wiki/Togo", "capital": "Lomé"},
    {"name": "Tonga", "iso3": "TON", "wikipage": "https://fr.wikipedia.org/wiki/Tonga", "capital": "Nukualofa"},
    {"name": "Trinité-et-Tobago", "iso3": "TTO", "wikipage": "https://fr.wikipedia.org/wiki/Trinit%C3%A9-et-Tobago", "capital": "Port of Spain"},
    {"name": "Tunisie", "iso3": "TUN", "wikipage": "https://fr.wikipedia.org/wiki/Tunisie", "capital": "Tunis"},
    {"name": "Turkménistan", "iso3": "TKM", "wikipage": "https://fr.wikipedia.org/wiki/Turkm%C3%A9nistan", "capital": "Achgabat"},
    {"name": "Turquie", "iso3": "TUR", "wikipage": "https://fr.wikipedia.org/wiki/Turquie", "capital": "Ankara"},
    {"name": "Tuvalu", "iso3": "TUV", "wikipage": "https://fr.wikipedia.org/wiki/Tuvalu", "capital": "Fanafuti"},
    {"name": "Ukraine", "iso3": "UKR", "wikipage": "https://fr.wikipedia.org/wiki/Ukraine", "capital": "Kiev"},
    {"name": "Uruguay", "iso3": "URY", "wikipage": "https://fr.wikipedia.org/wiki/Uruguay", "capital": "Montevideo"},
    {"name": "Vanuatu", "iso3": "VUT", "wikipage": "https://fr.wikipedia.org/wiki/Vanuatu", "capital": "Port-Vila"},
    {"name": "Venezuela", "iso3": "VEN", "wikipage": "https://fr.wikipedia.org/wiki/Venezuela", "capital": "Caracas"},
    {"name": "Viêt Nam", "iso3": "VNM", "wikipage": "https://fr.wikipedia.org/wiki/Vi%C3%AAt_Nam", "capital": "Hanoi"},
    {"name": "Yémen", "iso3": "YEM", "wikipage": "https://fr.wikipedia.org/wiki/Y%C3%A9men", "capital": "Sanaa"},
    {"name": "Zambie", "iso3": "ZMB", "wikipage": "https://fr.wikipedia.org/wiki/Zambie", "capital": "Lusaka"},
    {"name": "Zimbabwe", "iso3": "ZWE", "wikipage": "https://fr.wikipedia.org/wiki/Zimbabwe", "capital": "Harare"}
];

module.exports = {
    countryByName: (name) => {
        return _.find(countries, {"name": name});
    },

    countryByCapital: (capital) => {
        return _.find(countries, {"capital": capital});
    }
};